myapp/urls.py
from django.urls import path
app_name="myapp"
from myapp import views

urlpatterns=[
    path('base/',views.base,name='base'),
    path('profile/', views.profile,name='profile'),
    path('register/',views.register,name='register'),
    path('img_upld/',views.img_upld, name='img_upld'),
    path('img_disp/',views.img_disp,name='img_disp'),
]

p15/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('home/',views.home,name='home'),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG== True:
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.core.mail import send_mail

# Create your views here.
def base(request):
    return render(request,"base.html")
def profile(request):
    name='ASHOK'
    return render(request,"myapp/profile.html",{'name':name})
def home(request):
    return render(request,"myapp/home.html")
def register(request):
    if request.method=="POST":
        first_name= request.POST.get('first_name')
        last_name= request.POST.get('last_name')
        email= request.POST.get('email')
        password= request.POST.get('password')
        date= request.POST.get('date')
        send_mail('thanks for registration','mr./ms.{} {}'.format(first_name, last_name),'ashokbuengg@gmail.com',[email,],fail_silently=True)
        #return HttpResponse('<h1>{}<br>{}<br>{}<br>{}<br>{}</h1>'.format(first_name, last_name, email, password, date))
        return redirect("home")
    return render(request,"registration.html")

from django.core.files.storage import FileSystemStorage
def img_upld(request):
    return render(request,'img_upld.html')

from myapp.utilities import store_image
def img_disp(request):
    file_urls=False
    if request.method=="POST" and request.FILES:
        image1=request.FILES.get('img1')
        image2=request.FILES.get('img2')
        file_urls=map(store_image,[image1,image2])
    return render(request,"img_disp.html",context={'file_urls':file_urls})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>BASE HTML</title>
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'partials/_topbar.html' %}
    {% include 'partials/_navbar.html' %}
    {% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Welcome to BASE</h1>
        </div>
    </div>
    {% endblock %}
    {% include 'partials/_footer.html' %}
</body>
</html>

templates/img_disp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Display</title>
</head>
<body>
    {% for file_url in file_urls %}
    {% if file_url %}
    <img src="{{file_url}}" alt="no image found">
    {% endif %}
    {% endfor %}
</body>
</html>

templates/img_upld.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Upload</title>
</head>
<body>
    <form action="{% url 'myapp:img_disp' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        IMG1: <input type="file" name="img1" id="img1">
        IMG2: <input type="file" name="img2" id="img2">
        <input type="submit" value="submit">
    </form>
</body>
</html>

templates/myapp/home.html
{% extends 'base.html' %}
{% block title %}
    <title>Profile HTML</title>
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Welcome to HOME</h1>
    </div>
</div>
{% endblock %}

templates/myapp/profile.html
{% extends 'base.html' %}
{% block title %}
    <title>PROFILE HTML</title>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Welcome to {{name}} profile </h1>
        </div>
    </div>
    {% endblock %}

templates/partials/_footer.html
<!--foot bar-->
<div class="alert alert-secondary">
    <center>Footer</center>
</div>

templates/partials/_navbar.html
    <!--Nav Bar-->
    <div class="container">
      <ul class="nav">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:register' %}">Register</a>
          </li>
      </ul>
  </div>

templates/partials/_topbar.html
<!--TopBar-->
<div class="alert alert-primary">
    <center>TopBar</center>
</div>

templates/registration.html
{% extends 'base.html' %}
{% block title %}
    <title>REGISTRATION</title>
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <form method="post">
            {% csrf_token %}
            <label for="first_name">FIRST_NAME:</label>
            <input type="text" class="form-control" name="first_name" id="first_name"><br>
            <label for="last_name">LAST_NAME:</label>
            <input type="text" class="form-control" name="last_name" id="last_name"><br>
            <label for="email">E-mail:</label>
            <input type="email" class="form-control" name="email" id="email"><br>
            <label for="password">PASSWORD:</label>
            <input type="password" class="form-control" name="password" id="password"><br>
            <label for="date">DOB:</label>
            <input type="date" class="form-control" name="date" id="date"><br>
            <input type="submit" value="submit">
        </form>
    </div>
</div>
{% endblock %}